apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/site.conf;
    }
  site.conf: |
    server {
      listen 80 k8s.wfaw-10059.workfusion.com;
      root /usr/local/app;
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location /first/ {
        root /var/www/site/first/public_html;
        index  index.html index.htm;
      }
      location /second/ {
        root /var/www/site/second/public_html;
        index  index.html index.htm;
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: web-site
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:1.15-alpine
      #Пробрасываем порты
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          readOnly: true
          subPath: nginx.conf
          name: nginx-conf
        - mountPath: /var/www/site/first/public_html
          name: first-html
        - mountPath: /var/www/site/second/public_html
          name: second-html
      livenessProbe:
        # Время ожидания после запуска pod'ы до момента начала проверки
        initialDelaySeconds: 5
        periodSeconds: 10
        # http проверка
        httpGet:
          path: /
          port: 80
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
        items:
          - key: nginx.conf
            path: nginx.conf
          - key: site.conf
            path: conf.d/site.conf # dig directory
    - name: log
      emptyDir: { }
    - name: first-html
      hostPath:
        # directory location on host
        path: /opt/k8s/scand/web/data/scand/
        # this field is optional
        type: Directory
    - name: second-html
      hostPath:
        # directory location on host
        path: /opt/k8s/scand/web/data/home/
        # this field is optional
        type: Directory
