apiVersion: v1
kind: ConfigMap
metadata:
  name: site-conf
data:
  site.conf: |
    server {
      listen 80 k8s.wfaw-10059.workfusion.com;
      root /usr/local/app;
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location /first/ {
        root /var/www/site/first/public_html;
        index  index.html index.htm;
      }
      location /second/ {
        root /var/www/site/second/public_html;
        index  index.html index.htm;
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: web-site
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:1.15-alpine
      #Пробрасываем порты
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/site.conf
          readOnly: true
          subPath: site.conf
          name: site-conf
        - mountPath: /var/www/site/first/public_html
          name: first-html
        - mountPath: /var/www/site/second/public_html
          name: second-html
      livenessProbe:
        # Время ожидания после запуска pod'ы до момента начала проверки
        initialDelaySeconds: 5
        periodSeconds: 10
        # http проверка
        httpGet:
          path: /
          port: 80
  volumes:
    - name: site-conf
      configMap:
        name: site-conf # place ConfigMap `site-conf` on /etc/nginx/conf.d
    - name: log
      emptyDir: { }
    - name: first-html
      hostPath:
        # directory location on host
        path: /opt/k8s/scand/web/data/scand/
        # this field is optional
        type: Directory
    - name: second-html
      hostPath:
        # directory location on host
        path: /opt/k8s/scand/web/data/home/
        # this field is optional
        type: Directory
