---
apiVersion: v1
kind: Pod
metadata:
  name: web-site
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:1.15-alpine
      #Пробрасываем порты
      ports:
        - containerPort: 80
        - containerPort: 443
      livenessProbe:
        # включаем проверку работоспособности
        enabled: true
        type: http
        # Время ожидания после запуска pod'ы до момента начала проверки
