---
apiVersion: v1
kind: Pod
metadata:
  name: web-site
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:1.15-alpine
      #Пробрасываем порты
      ports:
        - containerPort: 80
        - containerPort: 443
      livenessProbe:
        # Время ожидания после запуска pod'ы до момента начала проверки
        initialDelaySeconds: 5
        periodSeconds: 10
        # http проверка
        httpGet:
          path: /
          port: 80
    - name: certbot
      image: certbot/certbot
