apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
    - hosts:
        - scand.workfusion.com
      secretName: scand-secret
  rules:
    - host: scand.workfusion.com
      http:
        paths:
          - path: /first
            pathType: Prefix
            backend:
              service:
                name: first-svc
                port:
                  number: 5678
          - path: /second
            pathType: Prefix
            backend:
              service:
                name: second-svc
                port:
                  number: 5678
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  number: 80
